name: booka_app
description: "Booka — аудіокниги українською"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.5
  dio: ^5.7.0
  dio_cache_interceptor: ^4.0.3
  path_provider: ^2.1.5
  http_cache_file_store: ^2.0.1
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  just_audio: ^0.10.4
  just_audio_background: ^0.0.1-beta.15
  google_fonts: ^6.2.1
  auto_size_text: ^3.0.0
  flutter_secure_storage: ^9.2.2
  cached_network_image: ^3.2.3
  google_sign_in: ^6.2.1
  permission_handler: ^12.0.1
  lottie: ^3.1.2
  flutter_native_splash: ^2.4.2

  # Push/локальные уведомления (можно оставить без пинов — подтянется совместимое)
  firebase_core:
  firebase_messaging:
  flutter_local_notifications:
  package_info_plus:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/logo.png
    - lib/assets/images/romance.png
    - lib/assets/images/fantasy.png
    - lib/assets/images/detective.png
    - assets/splash/booka_equalizer_loader.json

# Конфиг иконки приложения
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/app_icon/app_icon.png   # квадратный PNG 1024×1024
  min_sdk_android: 21
  # adaptive_icon_background: "#FFFFFF"        # или путь к картинке
  # adaptive_icon_foreground: assets/app_icon/adaptive_fg.png

flutter_native_splash:
  color: "#0B0B0C"
  color_dark: "#0B0B0C"
  image: assets/splash/logo_full.jpg
  image_dark: assets/splash/logo_full.jpg
  android_12:
    color: "#0B0B0C"
    image: assets/splash/logo_full.jpg
