name: booka_app
description: "Booka — аудіокниги українською"
publish_to: 'none'

version: 1.0.0+30

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.5
  dio: ^5.7.0
  dio_cache_interceptor: ^4.0.3
  path_provider: ^2.1.5
  http_cache_file_store: ^2.0.1
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  just_audio: ^0.10.4
  just_audio_background: ^0.0.1-beta.15
  google_fonts: ^6.2.1
  auto_size_text: ^3.0.0
  flutter_secure_storage: ^9.2.2
  cached_network_image: ^3.2.3
  google_sign_in: ^6.2.1
  permission_handler: ^12.0.1
  flutter_app_minimizer_plus: ^1.0.2

  # Push / локальні сповіщення (версії не фіксуємо, підтягнуться сумісні)
  firebase_core:
  firebase_messaging:
  flutter_local_notifications:
  package_info_plus:
  lottie: ^3.3.1
  google_mobile_ads: ^6.0.0
  in_app_purchase: ^3.2.3
  in_app_purchase_android: ^0.4.0+8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/logo.png
    - lib/assets/images/romance.png
    - lib/assets/images/fantasy.png
    - lib/assets/images/detective.png
    # Додаємо те, що реально є у проєкті й може використовуватися всередині застосунку:
    - assets/splash/logo.jpg
    - assets/splash/logo_full.jpg
    - assets/splash/logo512.jpg
    - assets/splash/booka_equalizer_loader.json

# Іконка застосунку
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/app_icon/app_icon.png    # квадратний PNG 1024×1024
  min_sdk_android: 21
  # adaptive_icon_background: "#FFFFFF"
  # adaptive_icon_foreground: assets/app_icon/adaptive_fg.png

# Нативний splash-screen. Використовуємо твоє logo.jpg як центральне зображення.
flutter_native_splash:
  android: true
  ios: true
  web: false
  fullscreen: true
  android_gravity: center
  ios_content_mode: center

  # Світла тема
  color: "#060303"
  image: assets/splash/logo.jpg

  # Темна тема
  color_dark: "#060303"
  image_dark: assets/splash/logo.jpg

  # Спеціальні вимоги Android 12+
  android_12:
    image: assets/splash/logo.jpg
    image_dark: assets/splash/logo.jpg
    icon_background_color: "#060303"
    icon_background_color_dark: "#121212"
